rules:
    - id: yap-secrets-hf-token-literal
      message: Do not commit HuggingFace token literals.
      severity: ERROR
      languages:
          - generic
      pattern-regex: 'hf_[A-Za-z0-9]{20,}'
