"""Training metric, diagnostic, and dashboard tunables."""

from __future__ import annotations

CONFIDENT_SCORE = 0.80
VERY_CONFIDENT_SCORE = 0.90
LOW_CONFIDENCE_SCORE = 0.60
CONFIDENCE_BUCKETS = (0.0, 0.5, 0.6, 0.7, 0.8, 0.9, 1.000001)
PROBABILITY_FLOOR = 1e-12
CHECKPOINT_ACCURACY_WEIGHT = 2.0

DASHBOARD_MIN_ELAPSED_SECONDS = 0.001
DASHBOARD_REFRESH_SECONDS = 0.2
DASHBOARD_PROGRESS_WIDTH = 28
DASHBOARD_SPARKLINE_WIDTH = 64
DASHBOARD_SMALL_FLOAT_THRESHOLD = 0.001
DASHBOARD_SPARKLINE_BLOCKS = "▁▂▃▄▅▆▇█"
